#ifndef __CPU_COUNT_H__
#define __CPU_COUNT_H__

#include <stdio.h>


#define DECLARE_STATIC_COUNTER(name) static int cnt_##name = 0;
#define COUNTER_FUNC(name)          \
    static inline void count_##name() {         \
        cnt_##name += 1;                 \
        flush_result();                  \
    }
// #define PRINT_COUNT(fp, name) if(cnt_##name>0){fprintf(fp, #name ", %d,\n", cnt_##name);}
#define PRINT_COUNT(fp, name) fprintf(fp, #name ", %d,\n", cnt_##name);

// 1. vector int Add/sub 2. vector logical 3. vector fp add/sub 4. vector fp mul 5. vector fp fma 6. vector int mul 7. vector int madd 8. gather 9. compress 10. reduction 11. vector load/store address mode 12.vset 13. slide 14. cross domain (int -> vector/fp -> vector) move 15. vector int div 16. int div 17. vector div/sqrt 18. vector fp div/sqrt 19. mask 20. Vecor fp convert
// DECLARE_COUNTERS
    DECLARE_STATIC_COUNTER(vmvxs);
    DECLARE_STATIC_COUNTER(vpopc);
    DECLARE_STATIC_COUNTER(vfirst);
    DECLARE_STATIC_COUNTER(vmvsx);
    DECLARE_STATIC_COUNTER(vzextvf8);
    DECLARE_STATIC_COUNTER(vsextvf8);
    DECLARE_STATIC_COUNTER(vzextvf4);
    DECLARE_STATIC_COUNTER(vsextvf4);
    DECLARE_STATIC_COUNTER(vzextvf2);
    DECLARE_STATIC_COUNTER(vsextvf2);
    DECLARE_STATIC_COUNTER(vbrev_v);
    DECLARE_STATIC_COUNTER(vbrev8_v);
    DECLARE_STATIC_COUNTER(vrev8_v);
    DECLARE_STATIC_COUNTER(vclz_v);
    DECLARE_STATIC_COUNTER(vcpop_v);
    DECLARE_STATIC_COUNTER(vctz_v);
    DECLARE_STATIC_COUNTER(vmsbf);
    DECLARE_STATIC_COUNTER(vmsof);
    DECLARE_STATIC_COUNTER(vmsif);
    DECLARE_STATIC_COUNTER(viota);
    DECLARE_STATIC_COUNTER(vid);
    DECLARE_STATIC_COUNTER(vfmvfs);
    DECLARE_STATIC_COUNTER(vfmvsf);
    DECLARE_STATIC_COUNTER(vfcvt_xufv);
    DECLARE_STATIC_COUNTER(vfcvt_xfv);
    DECLARE_STATIC_COUNTER(vfcvt_fxuv);
    DECLARE_STATIC_COUNTER(vfcvt_fxv);
    DECLARE_STATIC_COUNTER(vfcvt_rtz_xufv);
    DECLARE_STATIC_COUNTER(vfcvt_rtz_xfv);
    DECLARE_STATIC_COUNTER(vfwcvt_xufv);
    DECLARE_STATIC_COUNTER(vfwcvt_xfv);
    DECLARE_STATIC_COUNTER(vfwcvt_fxuv);
    DECLARE_STATIC_COUNTER(vfwcvt_fxv);
    DECLARE_STATIC_COUNTER(vfwcvt_ffv);
    DECLARE_STATIC_COUNTER(vfwcvt_rtz_xufv);
    DECLARE_STATIC_COUNTER(vfwcvt_rtz_xfv);
    DECLARE_STATIC_COUNTER(vfncvt_xufw);
    DECLARE_STATIC_COUNTER(vfncvt_xfw);
    DECLARE_STATIC_COUNTER(vfncvt_fxuw);
    DECLARE_STATIC_COUNTER(vfncvt_fxw);
    DECLARE_STATIC_COUNTER(vfncvt_ffw);
    DECLARE_STATIC_COUNTER(vfncvt_rod_ffw);
    DECLARE_STATIC_COUNTER(vfncvt_rtz_xufw);
    DECLARE_STATIC_COUNTER(vfncvt_rtz_xfw);
    DECLARE_STATIC_COUNTER(vfsqrt_v);
    DECLARE_STATIC_COUNTER(vfrsqrt7_v);
    DECLARE_STATIC_COUNTER(vfrec7_v);
    DECLARE_STATIC_COUNTER(vfclass_v);
    DECLARE_STATIC_COUNTER(vadd);
    DECLARE_STATIC_COUNTER(vsub);
    DECLARE_STATIC_COUNTER(vrsub);
    DECLARE_STATIC_COUNTER(vminu);
    DECLARE_STATIC_COUNTER(vmin);
    DECLARE_STATIC_COUNTER(vmaxu);
    DECLARE_STATIC_COUNTER(vmax);
    DECLARE_STATIC_COUNTER(vand);
    DECLARE_STATIC_COUNTER(vor);
    DECLARE_STATIC_COUNTER(vxor);
    DECLARE_STATIC_COUNTER(vrgather);
    DECLARE_STATIC_COUNTER(vrgatherei16);
    DECLARE_STATIC_COUNTER(vadc);
    DECLARE_STATIC_COUNTER(vmadc);
    DECLARE_STATIC_COUNTER(vsbc);
    DECLARE_STATIC_COUNTER(vmsbc);
    DECLARE_STATIC_COUNTER(vmerge);
    DECLARE_STATIC_COUNTER(vmseq);
    DECLARE_STATIC_COUNTER(vmsne);
    DECLARE_STATIC_COUNTER(vmsltu);
    DECLARE_STATIC_COUNTER(vmslt);
    DECLARE_STATIC_COUNTER(vmsleu);
    DECLARE_STATIC_COUNTER(vmsle);
    DECLARE_STATIC_COUNTER(vmsgtu);
    DECLARE_STATIC_COUNTER(vmsgt);
    DECLARE_STATIC_COUNTER(vsaddu);
    DECLARE_STATIC_COUNTER(vsadd);
    DECLARE_STATIC_COUNTER(vssubu);
    DECLARE_STATIC_COUNTER(vssub);
    DECLARE_STATIC_COUNTER(vsll);
    DECLARE_STATIC_COUNTER(vmvnr);
    DECLARE_STATIC_COUNTER(vsmul);
    DECLARE_STATIC_COUNTER(vsrl);
    DECLARE_STATIC_COUNTER(vsra);
    DECLARE_STATIC_COUNTER(vssra);
    DECLARE_STATIC_COUNTER(vnsrl);
    DECLARE_STATIC_COUNTER(vnsra);
    DECLARE_STATIC_COUNTER(vnclipu);
    DECLARE_STATIC_COUNTER(vnclip);
    DECLARE_STATIC_COUNTER(vssrl);
    DECLARE_STATIC_COUNTER(vwredsumu);
    DECLARE_STATIC_COUNTER(vwredsum);
    DECLARE_STATIC_COUNTER(vdotu);
    DECLARE_STATIC_COUNTER(vdot);
    DECLARE_STATIC_COUNTER(vwsmaccu);
    DECLARE_STATIC_COUNTER(vwsmacc);
    DECLARE_STATIC_COUNTER(vwsmaccsu);
    DECLARE_STATIC_COUNTER(vwsmaccus);
    DECLARE_STATIC_COUNTER(vandn);
    DECLARE_STATIC_COUNTER(vrol);
    DECLARE_STATIC_COUNTER(vror);
    DECLARE_STATIC_COUNTER(vwsll);
    DECLARE_STATIC_COUNTER(vslideup);
    DECLARE_STATIC_COUNTER(vslidedown);
    DECLARE_STATIC_COUNTER(vredsum);
    DECLARE_STATIC_COUNTER(vredand);
    DECLARE_STATIC_COUNTER(vredor);
    DECLARE_STATIC_COUNTER(vredxor);
    DECLARE_STATIC_COUNTER(vredminu);
    DECLARE_STATIC_COUNTER(vredmin);
    DECLARE_STATIC_COUNTER(vredmaxu);
    DECLARE_STATIC_COUNTER(vredmax);
    DECLARE_STATIC_COUNTER(vaaddu);
    DECLARE_STATIC_COUNTER(vaadd);
    DECLARE_STATIC_COUNTER(vasubu);
    DECLARE_STATIC_COUNTER(vasub);
    DECLARE_STATIC_COUNTER(vwxunary0_dispatch);
    DECLARE_STATIC_COUNTER(vmunary0_dispatch);
    DECLARE_STATIC_COUNTER(vcompress);
    DECLARE_STATIC_COUNTER(vmandnot);
    DECLARE_STATIC_COUNTER(vmand);
    DECLARE_STATIC_COUNTER(vmor);
    DECLARE_STATIC_COUNTER(vmxor);
    DECLARE_STATIC_COUNTER(vmornot);
    DECLARE_STATIC_COUNTER(vmnand);
    DECLARE_STATIC_COUNTER(vmnor);
    DECLARE_STATIC_COUNTER(vmxnor);
    DECLARE_STATIC_COUNTER(vdivu);
    DECLARE_STATIC_COUNTER(vdiv);
    DECLARE_STATIC_COUNTER(vremu);
    DECLARE_STATIC_COUNTER(vrem);
    DECLARE_STATIC_COUNTER(vmulhu);
    DECLARE_STATIC_COUNTER(vmul);
    DECLARE_STATIC_COUNTER(vmulhsu);
    DECLARE_STATIC_COUNTER(vmulh);
    DECLARE_STATIC_COUNTER(vmadd);
    DECLARE_STATIC_COUNTER(vnmsub);
    DECLARE_STATIC_COUNTER(vmacc);
    DECLARE_STATIC_COUNTER(vnmsac);
    DECLARE_STATIC_COUNTER(vwaddu);
    DECLARE_STATIC_COUNTER(vwadd);
    DECLARE_STATIC_COUNTER(vwsubu);
    DECLARE_STATIC_COUNTER(vwsub);
    DECLARE_STATIC_COUNTER(vwaddu_w);
    DECLARE_STATIC_COUNTER(vwadd_w);
    DECLARE_STATIC_COUNTER(vwsubu_w);
    DECLARE_STATIC_COUNTER(vwsub_w);
    DECLARE_STATIC_COUNTER(vwmulu);
    DECLARE_STATIC_COUNTER(vwmulsu);
    DECLARE_STATIC_COUNTER(vwmul);
    DECLARE_STATIC_COUNTER(vwmaccu);
    DECLARE_STATIC_COUNTER(vwmacc);
    DECLARE_STATIC_COUNTER(vwmaccus);
    DECLARE_STATIC_COUNTER(vwmaccsu);
    DECLARE_STATIC_COUNTER(vslide1up);
    DECLARE_STATIC_COUNTER(vslide1down);
    DECLARE_STATIC_COUNTER(vrxunary0_dispatch);
    DECLARE_STATIC_COUNTER(vfadd);
    DECLARE_STATIC_COUNTER(vfredusum);
    DECLARE_STATIC_COUNTER(vfsub);
    DECLARE_STATIC_COUNTER(vfredosum);
    DECLARE_STATIC_COUNTER(vfmin);
    DECLARE_STATIC_COUNTER(vfredmin);
    DECLARE_STATIC_COUNTER(vfmax);
    DECLARE_STATIC_COUNTER(vfredmax);
    DECLARE_STATIC_COUNTER(vfsgnj);
    DECLARE_STATIC_COUNTER(vfsgnjn);
    DECLARE_STATIC_COUNTER(vfsgnjx);
    DECLARE_STATIC_COUNTER(vwfunary0_dispatch);
    DECLARE_STATIC_COUNTER(vmfeq);
    DECLARE_STATIC_COUNTER(vmfle);
    DECLARE_STATIC_COUNTER(vmflt);
    DECLARE_STATIC_COUNTER(vmfne);
    DECLARE_STATIC_COUNTER(vfdiv);
    DECLARE_STATIC_COUNTER(vfmul);
    DECLARE_STATIC_COUNTER(vfmadd);
    DECLARE_STATIC_COUNTER(vfnmadd);
    DECLARE_STATIC_COUNTER(vfmsub);
    DECLARE_STATIC_COUNTER(vfnmsub);
    DECLARE_STATIC_COUNTER(vfmacc);
    DECLARE_STATIC_COUNTER(vfnmacc);
    DECLARE_STATIC_COUNTER(vfmsac);
    DECLARE_STATIC_COUNTER(vfnmsac);
    DECLARE_STATIC_COUNTER(vfwadd);
    DECLARE_STATIC_COUNTER(vfwredusum);
    DECLARE_STATIC_COUNTER(vfwsub);
    DECLARE_STATIC_COUNTER(vfwredosum);
    DECLARE_STATIC_COUNTER(vfwadd_w);
    DECLARE_STATIC_COUNTER(vfwsub_w);
    DECLARE_STATIC_COUNTER(vfwmul);
    DECLARE_STATIC_COUNTER(vfwmacc);
    DECLARE_STATIC_COUNTER(vfwnmacc);
    DECLARE_STATIC_COUNTER(vfwmsac);
    DECLARE_STATIC_COUNTER(vfwnmsac);
    DECLARE_STATIC_COUNTER(vfslide1up);
    DECLARE_STATIC_COUNTER(vfslide1down);
    DECLARE_STATIC_COUNTER(vrfunary0_dispatch);
    DECLARE_STATIC_COUNTER(vfmerge);
    DECLARE_STATIC_COUNTER(vmfgt);
    DECLARE_STATIC_COUNTER(vmfge);
    DECLARE_STATIC_COUNTER(vfrdiv);
    DECLARE_STATIC_COUNTER(vfrsub);
    DECLARE_STATIC_COUNTER(vsetvli);
    DECLARE_STATIC_COUNTER(vsetivli);
    DECLARE_STATIC_COUNTER(vsetvl);
    DECLARE_STATIC_COUNTER(vopivv);
    DECLARE_STATIC_COUNTER(vopfvv);
    DECLARE_STATIC_COUNTER(vopmvv);
    DECLARE_STATIC_COUNTER(vopivi);
    DECLARE_STATIC_COUNTER(vopivx);
    DECLARE_STATIC_COUNTER(vopfvf);
    DECLARE_STATIC_COUNTER(vopmvx);
    DECLARE_STATIC_COUNTER(vsetvl_dispatch); 

    DECLARE_STATIC_COUNTER(vle);     
    DECLARE_STATIC_COUNTER(vleff);   
    DECLARE_STATIC_COUNTER(vlr);     
    // DECLARE_STATIC_COUNTER(vlr);     
    // DECLARE_STATIC_COUNTER(vlr);     
    // DECLARE_STATIC_COUNTER(vlr);     
    DECLARE_STATIC_COUNTER(vlm);     
    DECLARE_STATIC_COUNTER(vlxe);    
    DECLARE_STATIC_COUNTER(vlse);    
    // DECLARE_STATIC_COUNTER(vlxe);    
    DECLARE_STATIC_COUNTER(vse);     
    DECLARE_STATIC_COUNTER(vsr);     
    // DECLARE_STATIC_COUNTER(vsr);     
    // DECLARE_STATIC_COUNTER(vsr);     
    // DECLARE_STATIC_COUNTER(vsr);     
    DECLARE_STATIC_COUNTER(vsm);     
    DECLARE_STATIC_COUNTER(vsxe);    
    DECLARE_STATIC_COUNTER(vsse);    
    // DECLARE_STATIC_COUNTER(vsxe);    
    DECLARE_STATIC_COUNTER(vle_mmu); 
    DECLARE_STATIC_COUNTER(vleff_mmu)
    // DECLARE_STATIC_COUNTER(vle_mmu); 
    DECLARE_STATIC_COUNTER(vlr_mmu); 
    // DECLARE_STATIC_COUNTER(vlr_mmu); 
    // DECLARE_STATIC_COUNTER(vlr_mmu); 
    // DECLARE_STATIC_COUNTER(vlr_mmu); 
    DECLARE_STATIC_COUNTER(vlm_mmu); 
    DECLARE_STATIC_COUNTER(vlxe_mmu);
    DECLARE_STATIC_COUNTER(vlse_mmu);
    // DECLARE_STATIC_COUNTER(vlxe_mmu);
    DECLARE_STATIC_COUNTER(vse_mmu); 
    DECLARE_STATIC_COUNTER(vsr_mmu); 
    // DECLARE_STATIC_COUNTER(vsr_mmu); 
    // DECLARE_STATIC_COUNTER(vsr_mmu); 
    // DECLARE_STATIC_COUNTER( vsr_mmu);
    DECLARE_STATIC_COUNTER(vsm_mmu); 
    DECLARE_STATIC_COUNTER(vsxe_mmu);
    DECLARE_STATIC_COUNTER(vsse_mmu);
    // DECLARE_STATIC_COUNTER(vsxe_mmu);



static inline int flush_result(){
    FILE *fp = fopen("/nfs/home/xutongqiao/vector/xs-env/NEMU/count.csv", "w");  // "w" 模式会清空原内容

    if (fp == NULL) {
        perror("打开文件失败");
        return 1;
    }
    //PRINT_COUNTS
        PRINT_COUNT(fp, vmvxs);
        PRINT_COUNT(fp, vpopc);
        PRINT_COUNT(fp, vfirst);
        PRINT_COUNT(fp, vmvsx);
        PRINT_COUNT(fp, vzextvf8);
        PRINT_COUNT(fp, vsextvf8);
        PRINT_COUNT(fp, vzextvf4);
        PRINT_COUNT(fp, vsextvf4);
        PRINT_COUNT(fp, vzextvf2);
        PRINT_COUNT(fp, vsextvf2);
        PRINT_COUNT(fp, vbrev_v);
        PRINT_COUNT(fp, vbrev8_v);
        PRINT_COUNT(fp, vrev8_v);
        PRINT_COUNT(fp, vclz_v);
        PRINT_COUNT(fp, vcpop_v);
        PRINT_COUNT(fp, vctz_v);
        PRINT_COUNT(fp, vmsbf);
        PRINT_COUNT(fp, vmsof);
        PRINT_COUNT(fp, vmsif);
        PRINT_COUNT(fp, viota);
        PRINT_COUNT(fp, vid);
        PRINT_COUNT(fp, vfmvfs);
        PRINT_COUNT(fp, vfmvsf);
        PRINT_COUNT(fp, vfcvt_xufv);
        PRINT_COUNT(fp, vfcvt_xfv);
        PRINT_COUNT(fp, vfcvt_fxuv);
        PRINT_COUNT(fp, vfcvt_fxv);
        PRINT_COUNT(fp, vfcvt_rtz_xufv);
        PRINT_COUNT(fp, vfcvt_rtz_xfv);
        PRINT_COUNT(fp, vfwcvt_xufv);
        PRINT_COUNT(fp, vfwcvt_xfv);
        PRINT_COUNT(fp, vfwcvt_fxuv);
        PRINT_COUNT(fp, vfwcvt_fxv);
        PRINT_COUNT(fp, vfwcvt_ffv);
        PRINT_COUNT(fp, vfwcvt_rtz_xufv);
        PRINT_COUNT(fp, vfwcvt_rtz_xfv);
        PRINT_COUNT(fp, vfncvt_xufw);
        PRINT_COUNT(fp, vfncvt_xfw);
        PRINT_COUNT(fp, vfncvt_fxuw);
        PRINT_COUNT(fp, vfncvt_fxw);
        PRINT_COUNT(fp, vfncvt_ffw);
        PRINT_COUNT(fp, vfncvt_rod_ffw);
        PRINT_COUNT(fp, vfncvt_rtz_xufw);
        PRINT_COUNT(fp, vfncvt_rtz_xfw);
        PRINT_COUNT(fp, vfsqrt_v);
        PRINT_COUNT(fp, vfrsqrt7_v);
        PRINT_COUNT(fp, vfrec7_v);
        PRINT_COUNT(fp, vfclass_v);
        PRINT_COUNT(fp, vadd);
        PRINT_COUNT(fp, vsub);
        PRINT_COUNT(fp, vrsub);
        PRINT_COUNT(fp, vminu);
        PRINT_COUNT(fp, vmin);
        PRINT_COUNT(fp, vmaxu);
        PRINT_COUNT(fp, vmax);
        PRINT_COUNT(fp, vand);
        PRINT_COUNT(fp, vor);
        PRINT_COUNT(fp, vxor);
        PRINT_COUNT(fp, vrgather);
        PRINT_COUNT(fp, vrgatherei16);
        PRINT_COUNT(fp, vadc);
        PRINT_COUNT(fp, vmadc);
        PRINT_COUNT(fp, vsbc);
        PRINT_COUNT(fp, vmsbc);
        PRINT_COUNT(fp, vmerge);
        PRINT_COUNT(fp, vmseq);
        PRINT_COUNT(fp, vmsne);
        PRINT_COUNT(fp, vmsltu);
        PRINT_COUNT(fp, vmslt);
        PRINT_COUNT(fp, vmsleu);
        PRINT_COUNT(fp, vmsle);
        PRINT_COUNT(fp, vmsgtu);
        PRINT_COUNT(fp, vmsgt);
        PRINT_COUNT(fp, vsaddu);
        PRINT_COUNT(fp, vsadd);
        PRINT_COUNT(fp, vssubu);
        PRINT_COUNT(fp, vssub);
        PRINT_COUNT(fp, vsll);
        PRINT_COUNT(fp, vmvnr);
        PRINT_COUNT(fp, vsmul);
        PRINT_COUNT(fp, vsrl);
        PRINT_COUNT(fp, vsra);
        PRINT_COUNT(fp, vssra);
        PRINT_COUNT(fp, vnsrl);
        PRINT_COUNT(fp, vnsra);
        PRINT_COUNT(fp, vnclipu);
        PRINT_COUNT(fp, vnclip);
        PRINT_COUNT(fp, vssrl);
        PRINT_COUNT(fp, vwredsumu);
        PRINT_COUNT(fp, vwredsum);
        PRINT_COUNT(fp, vdotu);
        PRINT_COUNT(fp, vdot);
        PRINT_COUNT(fp, vwsmaccu);
        PRINT_COUNT(fp, vwsmacc);
        PRINT_COUNT(fp, vwsmaccsu);
        PRINT_COUNT(fp, vwsmaccus);
        PRINT_COUNT(fp, vandn);
        PRINT_COUNT(fp, vrol);
        PRINT_COUNT(fp, vror);
        PRINT_COUNT(fp, vwsll);
        PRINT_COUNT(fp, vslideup);
        PRINT_COUNT(fp, vslidedown);
        PRINT_COUNT(fp, vredsum);
        PRINT_COUNT(fp, vredand);
        PRINT_COUNT(fp, vredor);
        PRINT_COUNT(fp, vredxor);
        PRINT_COUNT(fp, vredminu);
        PRINT_COUNT(fp, vredmin);
        PRINT_COUNT(fp, vredmaxu);
        PRINT_COUNT(fp, vredmax);
        PRINT_COUNT(fp, vaaddu);
        PRINT_COUNT(fp, vaadd);
        PRINT_COUNT(fp, vasubu);
        PRINT_COUNT(fp, vasub);
        PRINT_COUNT(fp, vwxunary0_dispatch);
        PRINT_COUNT(fp, vmunary0_dispatch);
        PRINT_COUNT(fp, vcompress);
        PRINT_COUNT(fp, vmandnot);
        PRINT_COUNT(fp, vmand);
        PRINT_COUNT(fp, vmor);
        PRINT_COUNT(fp, vmxor);
        PRINT_COUNT(fp, vmornot);
        PRINT_COUNT(fp, vmnand);
        PRINT_COUNT(fp, vmnor);
        PRINT_COUNT(fp, vmxnor);
        PRINT_COUNT(fp, vdivu);
        PRINT_COUNT(fp, vdiv);
        PRINT_COUNT(fp, vremu);
        PRINT_COUNT(fp, vrem);
        PRINT_COUNT(fp, vmulhu);
        PRINT_COUNT(fp, vmul);
        PRINT_COUNT(fp, vmulhsu);
        PRINT_COUNT(fp, vmulh);
        PRINT_COUNT(fp, vmadd);
        PRINT_COUNT(fp, vnmsub);
        PRINT_COUNT(fp, vmacc);
        PRINT_COUNT(fp, vnmsac);
        PRINT_COUNT(fp, vwaddu);
        PRINT_COUNT(fp, vwadd);
        PRINT_COUNT(fp, vwsubu);
        PRINT_COUNT(fp, vwsub);
        PRINT_COUNT(fp, vwaddu_w);
        PRINT_COUNT(fp, vwadd_w);
        PRINT_COUNT(fp, vwsubu_w);
        PRINT_COUNT(fp, vwsub_w);
        PRINT_COUNT(fp, vwmulu);
        PRINT_COUNT(fp, vwmulsu);
        PRINT_COUNT(fp, vwmul);
        PRINT_COUNT(fp, vwmaccu);
        PRINT_COUNT(fp, vwmacc);
        PRINT_COUNT(fp, vwmaccus);
        PRINT_COUNT(fp, vwmaccsu);
        PRINT_COUNT(fp, vslide1up);
        PRINT_COUNT(fp, vslide1down);
        PRINT_COUNT(fp, vrxunary0_dispatch);
        PRINT_COUNT(fp, vfadd);
        PRINT_COUNT(fp, vfredusum);
        PRINT_COUNT(fp, vfsub);
        PRINT_COUNT(fp, vfredosum);
        PRINT_COUNT(fp, vfmin);
        PRINT_COUNT(fp, vfredmin);
        PRINT_COUNT(fp, vfmax);
        PRINT_COUNT(fp, vfredmax);
        PRINT_COUNT(fp, vfsgnj);
        PRINT_COUNT(fp, vfsgnjn);
        PRINT_COUNT(fp, vfsgnjx);
        PRINT_COUNT(fp, vwfunary0_dispatch);
        PRINT_COUNT(fp, vmfeq);
        PRINT_COUNT(fp, vmfle);
        PRINT_COUNT(fp, vmflt);
        PRINT_COUNT(fp, vmfne);
        PRINT_COUNT(fp, vfdiv);
        PRINT_COUNT(fp, vfmul);
        PRINT_COUNT(fp, vfmadd);
        PRINT_COUNT(fp, vfnmadd);
        PRINT_COUNT(fp, vfmsub);
        PRINT_COUNT(fp, vfnmsub);
        PRINT_COUNT(fp, vfmacc);
        PRINT_COUNT(fp, vfnmacc);
        PRINT_COUNT(fp, vfmsac);
        PRINT_COUNT(fp, vfnmsac);
        PRINT_COUNT(fp, vfwadd);
        PRINT_COUNT(fp, vfwredusum);
        PRINT_COUNT(fp, vfwsub);
        PRINT_COUNT(fp, vfwredosum);
        PRINT_COUNT(fp, vfwadd_w);
        PRINT_COUNT(fp, vfwsub_w);
        PRINT_COUNT(fp, vfwmul);
        PRINT_COUNT(fp, vfwmacc);
        PRINT_COUNT(fp, vfwnmacc);
        PRINT_COUNT(fp, vfwmsac);
        PRINT_COUNT(fp, vfwnmsac);
        PRINT_COUNT(fp, vfslide1up);
        PRINT_COUNT(fp, vfslide1down);
        PRINT_COUNT(fp, vrfunary0_dispatch);
        PRINT_COUNT(fp, vfmerge);
        PRINT_COUNT(fp, vmfgt);
        PRINT_COUNT(fp, vmfge);
        PRINT_COUNT(fp, vfrdiv);
        PRINT_COUNT(fp, vfrsub);
        PRINT_COUNT(fp, vsetvli);
        PRINT_COUNT(fp, vsetivli);
        PRINT_COUNT(fp, vsetvl);
        PRINT_COUNT(fp, vopivv);
        PRINT_COUNT(fp, vopfvv);
        PRINT_COUNT(fp, vopmvv);
        PRINT_COUNT(fp, vopivi);
        PRINT_COUNT(fp, vopivx);
        PRINT_COUNT(fp, vopfvf);
        PRINT_COUNT(fp, vopmvx);
        PRINT_COUNT(fp, vsetvl_dispatch);   
           
        PRINT_COUNT(fp, vle);     
        PRINT_COUNT(fp, vleff);   
        PRINT_COUNT(fp, vlr);      
        PRINT_COUNT(fp, vlm);     
        PRINT_COUNT(fp, vlxe);    
        PRINT_COUNT(fp, vlse);     
        PRINT_COUNT(fp, vse);     
        PRINT_COUNT(fp, vsr);       
        PRINT_COUNT(fp, vsm);     
        PRINT_COUNT(fp, vsxe);    
        PRINT_COUNT(fp, vsse);      
        PRINT_COUNT(fp, vle_mmu); 
        PRINT_COUNT(fp, vleff_mmu)
        PRINT_COUNT(fp, vlr_mmu); 
        PRINT_COUNT(fp, vlm_mmu); 
        PRINT_COUNT(fp, vlxe_mmu);
        PRINT_COUNT(fp, vlse_mmu);
        PRINT_COUNT(fp, vse_mmu); 
        PRINT_COUNT(fp, vsr_mmu); 
        PRINT_COUNT(fp, vsm_mmu); 
        PRINT_COUNT(fp, vsxe_mmu);
        PRINT_COUNT(fp, vsse_mmu);
    fclose(fp);
    return 0;
}

// COUNTER_FUNCS
    COUNTER_FUNC(vmvxs);
    COUNTER_FUNC(vpopc);
    COUNTER_FUNC(vfirst);
    COUNTER_FUNC(vmvsx);
    COUNTER_FUNC(vzextvf8);
    COUNTER_FUNC(vsextvf8);
    COUNTER_FUNC(vzextvf4);
    COUNTER_FUNC(vsextvf4);
    COUNTER_FUNC(vzextvf2);
    COUNTER_FUNC(vsextvf2);
    COUNTER_FUNC(vbrev_v);
    COUNTER_FUNC(vbrev8_v);
    COUNTER_FUNC(vrev8_v);
    COUNTER_FUNC(vclz_v);
    COUNTER_FUNC(vcpop_v);
    COUNTER_FUNC(vctz_v);
    COUNTER_FUNC(vmsbf);
    COUNTER_FUNC(vmsof);
    COUNTER_FUNC(vmsif);
    COUNTER_FUNC(viota);
    COUNTER_FUNC(vid);
    COUNTER_FUNC(vfmvfs);
    COUNTER_FUNC(vfmvsf);
    COUNTER_FUNC(vfcvt_xufv);
    COUNTER_FUNC(vfcvt_xfv);
    COUNTER_FUNC(vfcvt_fxuv);
    COUNTER_FUNC(vfcvt_fxv);
    COUNTER_FUNC(vfcvt_rtz_xufv);
    COUNTER_FUNC(vfcvt_rtz_xfv);
    COUNTER_FUNC(vfwcvt_xufv);
    COUNTER_FUNC(vfwcvt_xfv);
    COUNTER_FUNC(vfwcvt_fxuv);
    COUNTER_FUNC(vfwcvt_fxv);
    COUNTER_FUNC(vfwcvt_ffv);
    COUNTER_FUNC(vfwcvt_rtz_xufv);
    COUNTER_FUNC(vfwcvt_rtz_xfv);
    COUNTER_FUNC(vfncvt_xufw);
    COUNTER_FUNC(vfncvt_xfw);
    COUNTER_FUNC(vfncvt_fxuw);
    COUNTER_FUNC(vfncvt_fxw);
    COUNTER_FUNC(vfncvt_ffw);
    COUNTER_FUNC(vfncvt_rod_ffw);
    COUNTER_FUNC(vfncvt_rtz_xufw);
    COUNTER_FUNC(vfncvt_rtz_xfw);
    COUNTER_FUNC(vfsqrt_v);
    COUNTER_FUNC(vfrsqrt7_v);
    COUNTER_FUNC(vfrec7_v);
    COUNTER_FUNC(vfclass_v);
    COUNTER_FUNC(vadd);
    COUNTER_FUNC(vsub);
    COUNTER_FUNC(vrsub);
    COUNTER_FUNC(vminu);
    COUNTER_FUNC(vmin);
    COUNTER_FUNC(vmaxu);
    COUNTER_FUNC(vmax);
    COUNTER_FUNC(vand);
    COUNTER_FUNC(vor);
    COUNTER_FUNC(vxor);
    COUNTER_FUNC(vrgather);
    COUNTER_FUNC(vrgatherei16);
    COUNTER_FUNC(vadc);
    COUNTER_FUNC(vmadc);
    COUNTER_FUNC(vsbc);
    COUNTER_FUNC(vmsbc);
    COUNTER_FUNC(vmerge);
    COUNTER_FUNC(vmseq);
    COUNTER_FUNC(vmsne);
    COUNTER_FUNC(vmsltu);
    COUNTER_FUNC(vmslt);
    COUNTER_FUNC(vmsleu);
    COUNTER_FUNC(vmsle);
    COUNTER_FUNC(vmsgtu);
    COUNTER_FUNC(vmsgt);
    COUNTER_FUNC(vsaddu);
    COUNTER_FUNC(vsadd);
    COUNTER_FUNC(vssubu);
    COUNTER_FUNC(vssub);
    COUNTER_FUNC(vsll);
    COUNTER_FUNC(vmvnr);
    COUNTER_FUNC(vsmul);
    COUNTER_FUNC(vsrl);
    COUNTER_FUNC(vsra);
    COUNTER_FUNC(vssra);
    COUNTER_FUNC(vnsrl);
    COUNTER_FUNC(vnsra);
    COUNTER_FUNC(vnclipu);
    COUNTER_FUNC(vnclip);
    COUNTER_FUNC(vssrl);
    COUNTER_FUNC(vwredsumu);
    COUNTER_FUNC(vwredsum);
    COUNTER_FUNC(vdotu);
    COUNTER_FUNC(vdot);
    COUNTER_FUNC(vwsmaccu);
    COUNTER_FUNC(vwsmacc);
    COUNTER_FUNC(vwsmaccsu);
    COUNTER_FUNC(vwsmaccus);
    COUNTER_FUNC(vandn);
    COUNTER_FUNC(vrol);
    COUNTER_FUNC(vror);
    COUNTER_FUNC(vwsll);
    COUNTER_FUNC(vslideup);
    COUNTER_FUNC(vslidedown);
    COUNTER_FUNC(vredsum);
    COUNTER_FUNC(vredand);
    COUNTER_FUNC(vredor);
    COUNTER_FUNC(vredxor);
    COUNTER_FUNC(vredminu);
    COUNTER_FUNC(vredmin);
    COUNTER_FUNC(vredmaxu);
    COUNTER_FUNC(vredmax);
    COUNTER_FUNC(vaaddu);
    COUNTER_FUNC(vaadd);
    COUNTER_FUNC(vasubu);
    COUNTER_FUNC(vasub);
    COUNTER_FUNC(vwxunary0_dispatch);
    COUNTER_FUNC(vmunary0_dispatch);
    COUNTER_FUNC(vcompress);
    COUNTER_FUNC(vmandnot);
    COUNTER_FUNC(vmand);
    COUNTER_FUNC(vmor);
    COUNTER_FUNC(vmxor);
    COUNTER_FUNC(vmornot);
    COUNTER_FUNC(vmnand);
    COUNTER_FUNC(vmnor);
    COUNTER_FUNC(vmxnor);
    COUNTER_FUNC(vdivu);
    COUNTER_FUNC(vdiv);
    COUNTER_FUNC(vremu);
    COUNTER_FUNC(vrem);
    COUNTER_FUNC(vmulhu);
    COUNTER_FUNC(vmul);
    COUNTER_FUNC(vmulhsu);
    COUNTER_FUNC(vmulh);
    COUNTER_FUNC(vmadd);
    COUNTER_FUNC(vnmsub);
    COUNTER_FUNC(vmacc);
    COUNTER_FUNC(vnmsac);
    COUNTER_FUNC(vwaddu);
    COUNTER_FUNC(vwadd);
    COUNTER_FUNC(vwsubu);
    COUNTER_FUNC(vwsub);
    COUNTER_FUNC(vwaddu_w);
    COUNTER_FUNC(vwadd_w);
    COUNTER_FUNC(vwsubu_w);
    COUNTER_FUNC(vwsub_w);
    COUNTER_FUNC(vwmulu);
    COUNTER_FUNC(vwmulsu);
    COUNTER_FUNC(vwmul);
    COUNTER_FUNC(vwmaccu);
    COUNTER_FUNC(vwmacc);
    COUNTER_FUNC(vwmaccus);
    COUNTER_FUNC(vwmaccsu);
    COUNTER_FUNC(vslide1up);
    COUNTER_FUNC(vslide1down);
    COUNTER_FUNC(vrxunary0_dispatch);
    COUNTER_FUNC(vfadd);
    COUNTER_FUNC(vfredusum);
    COUNTER_FUNC(vfsub);
    COUNTER_FUNC(vfredosum);
    COUNTER_FUNC(vfmin);
    COUNTER_FUNC(vfredmin);
    COUNTER_FUNC(vfmax);
    COUNTER_FUNC(vfredmax);
    COUNTER_FUNC(vfsgnj);
    COUNTER_FUNC(vfsgnjn);
    COUNTER_FUNC(vfsgnjx);
    COUNTER_FUNC(vwfunary0_dispatch);
    COUNTER_FUNC(vmfeq);
    COUNTER_FUNC(vmfle);
    COUNTER_FUNC(vmflt);
    COUNTER_FUNC(vmfne);
    COUNTER_FUNC(vfdiv);
    COUNTER_FUNC(vfmul);
    COUNTER_FUNC(vfmadd);
    COUNTER_FUNC(vfnmadd);
    COUNTER_FUNC(vfmsub);
    COUNTER_FUNC(vfnmsub);
    COUNTER_FUNC(vfmacc);
    COUNTER_FUNC(vfnmacc);
    COUNTER_FUNC(vfmsac);
    COUNTER_FUNC(vfnmsac);
    COUNTER_FUNC(vfwadd);
    COUNTER_FUNC(vfwredusum);
    COUNTER_FUNC(vfwsub);
    COUNTER_FUNC(vfwredosum);
    COUNTER_FUNC(vfwadd_w);
    COUNTER_FUNC(vfwsub_w);
    COUNTER_FUNC(vfwmul);
    COUNTER_FUNC(vfwmacc);
    COUNTER_FUNC(vfwnmacc);
    COUNTER_FUNC(vfwmsac);
    COUNTER_FUNC(vfwnmsac);
    COUNTER_FUNC(vfslide1up);
    COUNTER_FUNC(vfslide1down);
    COUNTER_FUNC(vrfunary0_dispatch);
    COUNTER_FUNC(vfmerge);
    COUNTER_FUNC(vmfgt);
    COUNTER_FUNC(vmfge);
    COUNTER_FUNC(vfrdiv);
    COUNTER_FUNC(vfrsub);
    COUNTER_FUNC(vsetvli);
    COUNTER_FUNC(vsetivli);
    COUNTER_FUNC(vsetvl);
    COUNTER_FUNC(vopivv);
    COUNTER_FUNC(vopfvv);
    COUNTER_FUNC(vopmvv);
    COUNTER_FUNC(vopivi);
    COUNTER_FUNC(vopivx);
    COUNTER_FUNC(vopfvf);
    COUNTER_FUNC(vopmvx);
    COUNTER_FUNC(vsetvl_dispatch); 

    COUNTER_FUNC(vle);     
    COUNTER_FUNC(vleff);   
    COUNTER_FUNC(vlr);      
    COUNTER_FUNC(vlm);     
    COUNTER_FUNC(vlxe);    
    COUNTER_FUNC(vlse);     
    COUNTER_FUNC(vse);     
    COUNTER_FUNC(vsr);       
    COUNTER_FUNC(vsm);     
    COUNTER_FUNC(vsxe);    
    COUNTER_FUNC(vsse);      
    COUNTER_FUNC(vle_mmu); 
    COUNTER_FUNC(vleff_mmu)
    COUNTER_FUNC(vlr_mmu); 
    COUNTER_FUNC(vlm_mmu); 
    COUNTER_FUNC(vlxe_mmu);
    COUNTER_FUNC(vlse_mmu);
    COUNTER_FUNC(vse_mmu); 
    COUNTER_FUNC(vsr_mmu); 
    COUNTER_FUNC(vsm_mmu); 
    COUNTER_FUNC(vsxe_mmu);
    COUNTER_FUNC(vsse_mmu);
#endif