#ifndef __CPU_COUNT_H__
#define __CPU_COUNT_H__

#define MAX_VSEW 8
#define MAX_LMUL 8
#define MAX_NF 8

#include <stdio.h>

#define DECLARE_STATIC_COUNTER_EXTERN(name) extern int cnt_##name[MAX_VSEW][MAX_LMUL];
#define DECLARE_STATIC_COUNTER_LS_EXTERN(name) extern int cnt_ls_##name[MAX_VSEW][MAX_LMUL][MAX_NF];

// #define DECLARE_STATIC_COUNTER_LS_EXTERN(name) extern int cnt_##name[MAX_VSEW][MAX_LMUL];

// printf("vlmul: %d ", vtype->vsew); 
// printf("vsew: %d ", vtype->vlmul); 
// #define COUNTER_FUNC(name) 
//     static inline void count_##name(uint32_t vsew, uint32_t vlmul) { 
//         cnt_##name[vlmul][vsew] += 1; 
//         printf("vlmul: %d ", vlmul); 
//         printf("vsew: %d ", vsew); 
//     }
#define COUNTER_FUNC(name) \
    static inline void count_##name(uint32_t vsew, uint32_t vlmul) { \
        cnt_##name[vsew][vlmul] += 1; \
    }
#define COUNTER_LS_FUNC(name) \
static inline void count_ls_##name(uint64_t inst, uint32_t vsew, uint32_t vlmul) { \
    cnt_ls_##name[vsew][vlmul][(uint32_t)(inst>>29)] += 1; \
}

// #define PRINT_COUNT(fp, name) if(cnt_##name>0){fprintf(fp, #name ", %d,\n", cnt_##name);}
#define PRINT_COUNT(fp, name) \
    for(int i=0;i<MAX_VSEW;i++){ \
        for(int j =0;j<MAX_LMUL;j++){ \
            if (cnt_##name[i][j] > 0){ \
                fprintf(fp, #name ", %d, %d, -1, %d,\n", i, j, cnt_##name[i][j]); \
            } \
        } \
    }

#define PRINT_LS_COUNT(fp, name) \
for(int i=0;i<MAX_VSEW;i++){ \
    for(int j =0;j<MAX_LMUL;j++){ \
        for(int k =0;k<MAX_NF;k++){ \
            if (cnt_ls_##name[i][j][k] > 0){ \
                fprintf(fp, #name ", %d, %d, %d, %d,\n", i, j, k, cnt_ls_##name[i][j][k]); \
            } \
        } \
    } \
}

// 1. vector int Add/sub 2. vector logical 3. vector fp add/sub 4. vector fp mul 5. vector fp fma 6. vector int mul 7. vector int madd 8. gather 9. compress 10. reduction 11. vector load/store address mode 12.vset 13. slide 14. cross domain (int -> vector/fp -> vector) move 15. vector int div 16. int div 17. vector div/sqrt 18. vector fp div/sqrt 19. mask 20. Vecor fp convert

// // DECLARE_COUNTERS
    DECLARE_STATIC_COUNTER_EXTERN(vmvxs);
    DECLARE_STATIC_COUNTER_EXTERN(vpopc);
    DECLARE_STATIC_COUNTER_EXTERN(vfirst);
    DECLARE_STATIC_COUNTER_EXTERN(vmvsx);
    DECLARE_STATIC_COUNTER_EXTERN(vzextvf8);
    DECLARE_STATIC_COUNTER_EXTERN(vsextvf8);
    DECLARE_STATIC_COUNTER_EXTERN(vzextvf4);
    DECLARE_STATIC_COUNTER_EXTERN(vsextvf4);
    DECLARE_STATIC_COUNTER_EXTERN(vzextvf2);
    DECLARE_STATIC_COUNTER_EXTERN(vsextvf2);
    DECLARE_STATIC_COUNTER_EXTERN(vbrev_v);
    DECLARE_STATIC_COUNTER_EXTERN(vbrev8_v);
    DECLARE_STATIC_COUNTER_EXTERN(vrev8_v);
    DECLARE_STATIC_COUNTER_EXTERN(vclz_v);
    DECLARE_STATIC_COUNTER_EXTERN(vcpop_v);
    DECLARE_STATIC_COUNTER_EXTERN(vctz_v);
    DECLARE_STATIC_COUNTER_EXTERN(vmsbf);
    DECLARE_STATIC_COUNTER_EXTERN(vmsof);
    DECLARE_STATIC_COUNTER_EXTERN(vmsif);
    DECLARE_STATIC_COUNTER_EXTERN(viota);
    DECLARE_STATIC_COUNTER_EXTERN(vid);
    DECLARE_STATIC_COUNTER_EXTERN(vfmvfs);
    DECLARE_STATIC_COUNTER_EXTERN(vfmvsf);
    DECLARE_STATIC_COUNTER_EXTERN(vfcvt_xufv);
    DECLARE_STATIC_COUNTER_EXTERN(vfcvt_xfv);
    DECLARE_STATIC_COUNTER_EXTERN(vfcvt_fxuv);
    DECLARE_STATIC_COUNTER_EXTERN(vfcvt_fxv);
    DECLARE_STATIC_COUNTER_EXTERN(vfcvt_rtz_xufv);
    DECLARE_STATIC_COUNTER_EXTERN(vfcvt_rtz_xfv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_xufv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_xfv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_fxuv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_fxv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_ffv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_rtz_xufv);
    DECLARE_STATIC_COUNTER_EXTERN(vfwcvt_rtz_xfv);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_xufw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_xfw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_fxuw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_fxw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_ffw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_rod_ffw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_rtz_xufw);
    DECLARE_STATIC_COUNTER_EXTERN(vfncvt_rtz_xfw);
    DECLARE_STATIC_COUNTER_EXTERN(vfsqrt_v);
    DECLARE_STATIC_COUNTER_EXTERN(vfrsqrt7_v);
    DECLARE_STATIC_COUNTER_EXTERN(vfrec7_v);
    DECLARE_STATIC_COUNTER_EXTERN(vfclass_v);
    DECLARE_STATIC_COUNTER_EXTERN(vadd);
    DECLARE_STATIC_COUNTER_EXTERN(vsub);
    DECLARE_STATIC_COUNTER_EXTERN(vrsub);
    DECLARE_STATIC_COUNTER_EXTERN(vminu);
    DECLARE_STATIC_COUNTER_EXTERN(vmin);
    DECLARE_STATIC_COUNTER_EXTERN(vmaxu);
    DECLARE_STATIC_COUNTER_EXTERN(vmax);
    DECLARE_STATIC_COUNTER_EXTERN(vand);
    DECLARE_STATIC_COUNTER_EXTERN(vor);
    DECLARE_STATIC_COUNTER_EXTERN(vxor);
    DECLARE_STATIC_COUNTER_EXTERN(vrgather);
    DECLARE_STATIC_COUNTER_EXTERN(vrgatherei16);
    DECLARE_STATIC_COUNTER_EXTERN(vadc);
    DECLARE_STATIC_COUNTER_EXTERN(vmadc);
    DECLARE_STATIC_COUNTER_EXTERN(vsbc);
    DECLARE_STATIC_COUNTER_EXTERN(vmsbc);
    DECLARE_STATIC_COUNTER_EXTERN(vmerge);
    DECLARE_STATIC_COUNTER_EXTERN(vmseq);
    DECLARE_STATIC_COUNTER_EXTERN(vmsne);
    DECLARE_STATIC_COUNTER_EXTERN(vmsltu);
    DECLARE_STATIC_COUNTER_EXTERN(vmslt);
    DECLARE_STATIC_COUNTER_EXTERN(vmsleu);
    DECLARE_STATIC_COUNTER_EXTERN(vmsle);
    DECLARE_STATIC_COUNTER_EXTERN(vmsgtu);
    DECLARE_STATIC_COUNTER_EXTERN(vmsgt);
    DECLARE_STATIC_COUNTER_EXTERN(vsaddu);
    DECLARE_STATIC_COUNTER_EXTERN(vsadd);
    DECLARE_STATIC_COUNTER_EXTERN(vssubu);
    DECLARE_STATIC_COUNTER_EXTERN(vssub);
    DECLARE_STATIC_COUNTER_EXTERN(vsll);
    DECLARE_STATIC_COUNTER_EXTERN(vmvnr);
    DECLARE_STATIC_COUNTER_EXTERN(vsmul);
    DECLARE_STATIC_COUNTER_EXTERN(vsrl);
    DECLARE_STATIC_COUNTER_EXTERN(vsra);
    DECLARE_STATIC_COUNTER_EXTERN(vssra);
    DECLARE_STATIC_COUNTER_EXTERN(vnsrl);
    DECLARE_STATIC_COUNTER_EXTERN(vnsra);
    DECLARE_STATIC_COUNTER_EXTERN(vnclipu);
    DECLARE_STATIC_COUNTER_EXTERN(vnclip);
    DECLARE_STATIC_COUNTER_EXTERN(vssrl);
    DECLARE_STATIC_COUNTER_EXTERN(vwredsumu);
    DECLARE_STATIC_COUNTER_EXTERN(vwredsum);
    DECLARE_STATIC_COUNTER_EXTERN(vdotu);
    DECLARE_STATIC_COUNTER_EXTERN(vdot);
    DECLARE_STATIC_COUNTER_EXTERN(vwsmaccu);
    DECLARE_STATIC_COUNTER_EXTERN(vwsmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vwsmaccsu);
    DECLARE_STATIC_COUNTER_EXTERN(vwsmaccus);
    DECLARE_STATIC_COUNTER_EXTERN(vandn);
    DECLARE_STATIC_COUNTER_EXTERN(vrol);
    DECLARE_STATIC_COUNTER_EXTERN(vror);
    DECLARE_STATIC_COUNTER_EXTERN(vwsll);
    DECLARE_STATIC_COUNTER_EXTERN(vslideup);
    DECLARE_STATIC_COUNTER_EXTERN(vslidedown);
    DECLARE_STATIC_COUNTER_EXTERN(vredsum);
    DECLARE_STATIC_COUNTER_EXTERN(vredand);
    DECLARE_STATIC_COUNTER_EXTERN(vredor);
    DECLARE_STATIC_COUNTER_EXTERN(vredxor);
    DECLARE_STATIC_COUNTER_EXTERN(vredminu);
    DECLARE_STATIC_COUNTER_EXTERN(vredmin);
    DECLARE_STATIC_COUNTER_EXTERN(vredmaxu);
    DECLARE_STATIC_COUNTER_EXTERN(vredmax);
    DECLARE_STATIC_COUNTER_EXTERN(vaaddu);
    DECLARE_STATIC_COUNTER_EXTERN(vaadd);
    DECLARE_STATIC_COUNTER_EXTERN(vasubu);
    DECLARE_STATIC_COUNTER_EXTERN(vasub);
    DECLARE_STATIC_COUNTER_EXTERN(vwxunary0_dispatch);
    DECLARE_STATIC_COUNTER_EXTERN(vmunary0_dispatch);
    DECLARE_STATIC_COUNTER_EXTERN(vcompress);
    DECLARE_STATIC_COUNTER_EXTERN(vmandnot);
    DECLARE_STATIC_COUNTER_EXTERN(vmand);
    DECLARE_STATIC_COUNTER_EXTERN(vmor);
    DECLARE_STATIC_COUNTER_EXTERN(vmxor);
    DECLARE_STATIC_COUNTER_EXTERN(vmornot);
    DECLARE_STATIC_COUNTER_EXTERN(vmnand);
    DECLARE_STATIC_COUNTER_EXTERN(vmnor);
    DECLARE_STATIC_COUNTER_EXTERN(vmxnor);
    DECLARE_STATIC_COUNTER_EXTERN(vdivu);
    DECLARE_STATIC_COUNTER_EXTERN(vdiv);
    DECLARE_STATIC_COUNTER_EXTERN(vremu);
    DECLARE_STATIC_COUNTER_EXTERN(vrem);
    DECLARE_STATIC_COUNTER_EXTERN(vmulhu);
    DECLARE_STATIC_COUNTER_EXTERN(vmul);
    DECLARE_STATIC_COUNTER_EXTERN(vmulhsu);
    DECLARE_STATIC_COUNTER_EXTERN(vmulh);
    DECLARE_STATIC_COUNTER_EXTERN(vmadd);
    DECLARE_STATIC_COUNTER_EXTERN(vnmsub);
    DECLARE_STATIC_COUNTER_EXTERN(vmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vnmsac);
    DECLARE_STATIC_COUNTER_EXTERN(vwaddu);
    DECLARE_STATIC_COUNTER_EXTERN(vwadd);
    DECLARE_STATIC_COUNTER_EXTERN(vwsubu);
    DECLARE_STATIC_COUNTER_EXTERN(vwsub);
    DECLARE_STATIC_COUNTER_EXTERN(vwaddu_w);
    DECLARE_STATIC_COUNTER_EXTERN(vwadd_w);
    DECLARE_STATIC_COUNTER_EXTERN(vwsubu_w);
    DECLARE_STATIC_COUNTER_EXTERN(vwsub_w);
    DECLARE_STATIC_COUNTER_EXTERN(vwmulu);
    DECLARE_STATIC_COUNTER_EXTERN(vwmulsu);
    DECLARE_STATIC_COUNTER_EXTERN(vwmul);
    DECLARE_STATIC_COUNTER_EXTERN(vwmaccu);
    DECLARE_STATIC_COUNTER_EXTERN(vwmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vwmaccus);
    DECLARE_STATIC_COUNTER_EXTERN(vwmaccsu);
    DECLARE_STATIC_COUNTER_EXTERN(vslide1up);
    DECLARE_STATIC_COUNTER_EXTERN(vslide1down);
    DECLARE_STATIC_COUNTER_EXTERN(vrxunary0_dispatch);
    DECLARE_STATIC_COUNTER_EXTERN(vfadd);
    DECLARE_STATIC_COUNTER_EXTERN(vfredusum);
    DECLARE_STATIC_COUNTER_EXTERN(vfsub);
    DECLARE_STATIC_COUNTER_EXTERN(vfredosum);
    DECLARE_STATIC_COUNTER_EXTERN(vfmin);
    DECLARE_STATIC_COUNTER_EXTERN(vfredmin);
    DECLARE_STATIC_COUNTER_EXTERN(vfmax);
    DECLARE_STATIC_COUNTER_EXTERN(vfredmax);
    DECLARE_STATIC_COUNTER_EXTERN(vfsgnj);
    DECLARE_STATIC_COUNTER_EXTERN(vfsgnjn);
    DECLARE_STATIC_COUNTER_EXTERN(vfsgnjx);
    DECLARE_STATIC_COUNTER_EXTERN(vwfunary0_dispatch);
    DECLARE_STATIC_COUNTER_EXTERN(vmfeq);
    DECLARE_STATIC_COUNTER_EXTERN(vmfle);
    DECLARE_STATIC_COUNTER_EXTERN(vmflt);
    DECLARE_STATIC_COUNTER_EXTERN(vmfne);
    DECLARE_STATIC_COUNTER_EXTERN(vfdiv);
    DECLARE_STATIC_COUNTER_EXTERN(vfmul);
    DECLARE_STATIC_COUNTER_EXTERN(vfmadd);
    DECLARE_STATIC_COUNTER_EXTERN(vfnmadd);
    DECLARE_STATIC_COUNTER_EXTERN(vfmsub);
    DECLARE_STATIC_COUNTER_EXTERN(vfnmsub);
    DECLARE_STATIC_COUNTER_EXTERN(vfmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vfnmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vfmsac);
    DECLARE_STATIC_COUNTER_EXTERN(vfnmsac);
    DECLARE_STATIC_COUNTER_EXTERN(vfwadd);
    DECLARE_STATIC_COUNTER_EXTERN(vfwredusum);
    DECLARE_STATIC_COUNTER_EXTERN(vfwsub);
    DECLARE_STATIC_COUNTER_EXTERN(vfwredosum);
    DECLARE_STATIC_COUNTER_EXTERN(vfwadd_w);
    DECLARE_STATIC_COUNTER_EXTERN(vfwsub_w);
    DECLARE_STATIC_COUNTER_EXTERN(vfwmul);
    DECLARE_STATIC_COUNTER_EXTERN(vfwmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vfwnmacc);
    DECLARE_STATIC_COUNTER_EXTERN(vfwmsac);
    DECLARE_STATIC_COUNTER_EXTERN(vfwnmsac);
    DECLARE_STATIC_COUNTER_EXTERN(vfslide1up);
    DECLARE_STATIC_COUNTER_EXTERN(vfslide1down);
    DECLARE_STATIC_COUNTER_EXTERN(vrfunary0_dispatch);
    DECLARE_STATIC_COUNTER_EXTERN(vfmerge);
    DECLARE_STATIC_COUNTER_EXTERN(vmfgt);
    DECLARE_STATIC_COUNTER_EXTERN(vmfge);
    DECLARE_STATIC_COUNTER_EXTERN(vfrdiv);
    DECLARE_STATIC_COUNTER_EXTERN(vfrsub);
    DECLARE_STATIC_COUNTER_EXTERN(vsetvli);
    DECLARE_STATIC_COUNTER_EXTERN(vsetivli);
    DECLARE_STATIC_COUNTER_EXTERN(vsetvl);
    DECLARE_STATIC_COUNTER_EXTERN(vopivv);
    DECLARE_STATIC_COUNTER_EXTERN(vopfvv);
    DECLARE_STATIC_COUNTER_EXTERN(vopmvv);
    DECLARE_STATIC_COUNTER_EXTERN(vopivi);
    DECLARE_STATIC_COUNTER_EXTERN(vopivx);
    DECLARE_STATIC_COUNTER_EXTERN(vopfvf);
    DECLARE_STATIC_COUNTER_EXTERN(vopmvx);
    DECLARE_STATIC_COUNTER_EXTERN(vsetvl_dispatch); 

    DECLARE_STATIC_COUNTER_LS_EXTERN(vle);     
    DECLARE_STATIC_COUNTER_LS_EXTERN(vleff);   
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlr);   
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlm);     
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlxe);    
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlse);      
    DECLARE_STATIC_COUNTER_LS_EXTERN(vse);     
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsr);    
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsm);     
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsxe);    
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsse);      
    DECLARE_STATIC_COUNTER_LS_EXTERN(vle_mmu); 
    DECLARE_STATIC_COUNTER_LS_EXTERN(vleff_mmu);
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlr_mmu); 
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlm_mmu); 
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlxe_mmu);
    DECLARE_STATIC_COUNTER_LS_EXTERN(vlse_mmu);
    DECLARE_STATIC_COUNTER_LS_EXTERN(vse_mmu); 
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsr_mmu); 
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsm_mmu); 
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsxe_mmu);
    DECLARE_STATIC_COUNTER_LS_EXTERN(vsse_mmu);



static inline int flush_result(){
    printf("START FLUSH\n");
    extern char *main_argv_tqxu;
    printf("%s\n", main_argv_tqxu);
    
    FILE *fp = fopen("/nfs/home/xutongqiao/vector/xs-env/NEMU/count.csv", "w");  // "w" 模式会清空原内容

    if (fp == NULL) {
        perror("打开文件失败");
        return 1;
    }
    //PRINT_COUNTS
        PRINT_COUNT(fp, vmvxs);
        PRINT_COUNT(fp, vpopc);
        PRINT_COUNT(fp, vfirst);
        PRINT_COUNT(fp, vmvsx);
        PRINT_COUNT(fp, vzextvf8);
        PRINT_COUNT(fp, vsextvf8);
        PRINT_COUNT(fp, vzextvf4);
        PRINT_COUNT(fp, vsextvf4);
        PRINT_COUNT(fp, vzextvf2);
        PRINT_COUNT(fp, vsextvf2);
        PRINT_COUNT(fp, vbrev_v);
        PRINT_COUNT(fp, vbrev8_v);
        PRINT_COUNT(fp, vrev8_v);
        PRINT_COUNT(fp, vclz_v);
        PRINT_COUNT(fp, vcpop_v);
        PRINT_COUNT(fp, vctz_v);
        PRINT_COUNT(fp, vmsbf);
        PRINT_COUNT(fp, vmsof);
        PRINT_COUNT(fp, vmsif);
        PRINT_COUNT(fp, viota);
        PRINT_COUNT(fp, vid);
        PRINT_COUNT(fp, vfmvfs);
        PRINT_COUNT(fp, vfmvsf);
        PRINT_COUNT(fp, vfcvt_xufv);
        PRINT_COUNT(fp, vfcvt_xfv);
        PRINT_COUNT(fp, vfcvt_fxuv);
        PRINT_COUNT(fp, vfcvt_fxv);
        PRINT_COUNT(fp, vfcvt_rtz_xufv);
        PRINT_COUNT(fp, vfcvt_rtz_xfv);
        PRINT_COUNT(fp, vfwcvt_xufv);
        PRINT_COUNT(fp, vfwcvt_xfv);
        PRINT_COUNT(fp, vfwcvt_fxuv);
        PRINT_COUNT(fp, vfwcvt_fxv);
        PRINT_COUNT(fp, vfwcvt_ffv);
        PRINT_COUNT(fp, vfwcvt_rtz_xufv);
        PRINT_COUNT(fp, vfwcvt_rtz_xfv);
        PRINT_COUNT(fp, vfncvt_xufw);
        PRINT_COUNT(fp, vfncvt_xfw);
        PRINT_COUNT(fp, vfncvt_fxuw);
        PRINT_COUNT(fp, vfncvt_fxw);
        PRINT_COUNT(fp, vfncvt_ffw);
        PRINT_COUNT(fp, vfncvt_rod_ffw);
        PRINT_COUNT(fp, vfncvt_rtz_xufw);
        PRINT_COUNT(fp, vfncvt_rtz_xfw);
        PRINT_COUNT(fp, vfsqrt_v);
        PRINT_COUNT(fp, vfrsqrt7_v);
        PRINT_COUNT(fp, vfrec7_v);
        PRINT_COUNT(fp, vfclass_v);
        PRINT_COUNT(fp, vadd);
        PRINT_COUNT(fp, vsub);
        PRINT_COUNT(fp, vrsub);
        PRINT_COUNT(fp, vminu);
        PRINT_COUNT(fp, vmin);
        PRINT_COUNT(fp, vmaxu);
        PRINT_COUNT(fp, vmax);
        PRINT_COUNT(fp, vand);
        PRINT_COUNT(fp, vor);
        PRINT_COUNT(fp, vxor);
        PRINT_COUNT(fp, vrgather);
        PRINT_COUNT(fp, vrgatherei16);
        PRINT_COUNT(fp, vadc);
        PRINT_COUNT(fp, vmadc);
        PRINT_COUNT(fp, vsbc);
        PRINT_COUNT(fp, vmsbc);
        PRINT_COUNT(fp, vmerge);
        PRINT_COUNT(fp, vmseq);
        PRINT_COUNT(fp, vmsne);
        PRINT_COUNT(fp, vmsltu);
        PRINT_COUNT(fp, vmslt);
        PRINT_COUNT(fp, vmsleu);
        PRINT_COUNT(fp, vmsle);
        PRINT_COUNT(fp, vmsgtu);
        PRINT_COUNT(fp, vmsgt);
        PRINT_COUNT(fp, vsaddu);
        PRINT_COUNT(fp, vsadd);
        PRINT_COUNT(fp, vssubu);
        PRINT_COUNT(fp, vssub);
        PRINT_COUNT(fp, vsll);
        PRINT_COUNT(fp, vmvnr);
        PRINT_COUNT(fp, vsmul);
        PRINT_COUNT(fp, vsrl);
        PRINT_COUNT(fp, vsra);
        PRINT_COUNT(fp, vssra);
        PRINT_COUNT(fp, vnsrl);
        PRINT_COUNT(fp, vnsra);
        PRINT_COUNT(fp, vnclipu);
        PRINT_COUNT(fp, vnclip);
        PRINT_COUNT(fp, vssrl);
        PRINT_COUNT(fp, vwredsumu);
        PRINT_COUNT(fp, vwredsum);
        PRINT_COUNT(fp, vdotu);
        PRINT_COUNT(fp, vdot);
        PRINT_COUNT(fp, vwsmaccu);
        PRINT_COUNT(fp, vwsmacc);
        PRINT_COUNT(fp, vwsmaccsu);
        PRINT_COUNT(fp, vwsmaccus);
        PRINT_COUNT(fp, vandn);
        PRINT_COUNT(fp, vrol);
        PRINT_COUNT(fp, vror);
        PRINT_COUNT(fp, vwsll);
        PRINT_COUNT(fp, vslideup);
        PRINT_COUNT(fp, vslidedown);
        PRINT_COUNT(fp, vredsum);
        PRINT_COUNT(fp, vredand);
        PRINT_COUNT(fp, vredor);
        PRINT_COUNT(fp, vredxor);
        PRINT_COUNT(fp, vredminu);
        PRINT_COUNT(fp, vredmin);
        PRINT_COUNT(fp, vredmaxu);
        PRINT_COUNT(fp, vredmax);
        PRINT_COUNT(fp, vaaddu);
        PRINT_COUNT(fp, vaadd);
        PRINT_COUNT(fp, vasubu);
        PRINT_COUNT(fp, vasub);
        PRINT_COUNT(fp, vwxunary0_dispatch);
        PRINT_COUNT(fp, vmunary0_dispatch);
        PRINT_COUNT(fp, vcompress);
        PRINT_COUNT(fp, vmandnot);
        PRINT_COUNT(fp, vmand);
        PRINT_COUNT(fp, vmor);
        PRINT_COUNT(fp, vmxor);
        PRINT_COUNT(fp, vmornot);
        PRINT_COUNT(fp, vmnand);
        PRINT_COUNT(fp, vmnor);
        PRINT_COUNT(fp, vmxnor);
        PRINT_COUNT(fp, vdivu);
        PRINT_COUNT(fp, vdiv);
        PRINT_COUNT(fp, vremu);
        PRINT_COUNT(fp, vrem);
        PRINT_COUNT(fp, vmulhu);
        PRINT_COUNT(fp, vmul);
        PRINT_COUNT(fp, vmulhsu);
        PRINT_COUNT(fp, vmulh);
        PRINT_COUNT(fp, vmadd);
        PRINT_COUNT(fp, vnmsub);
        PRINT_COUNT(fp, vmacc);
        PRINT_COUNT(fp, vnmsac);
        PRINT_COUNT(fp, vwaddu);
        PRINT_COUNT(fp, vwadd);
        PRINT_COUNT(fp, vwsubu);
        PRINT_COUNT(fp, vwsub);
        PRINT_COUNT(fp, vwaddu_w);
        PRINT_COUNT(fp, vwadd_w);
        PRINT_COUNT(fp, vwsubu_w);
        PRINT_COUNT(fp, vwsub_w);
        PRINT_COUNT(fp, vwmulu);
        PRINT_COUNT(fp, vwmulsu);
        PRINT_COUNT(fp, vwmul);
        PRINT_COUNT(fp, vwmaccu);
        PRINT_COUNT(fp, vwmacc);
        PRINT_COUNT(fp, vwmaccus);
        PRINT_COUNT(fp, vwmaccsu);
        PRINT_COUNT(fp, vslide1up);
        PRINT_COUNT(fp, vslide1down);
        PRINT_COUNT(fp, vrxunary0_dispatch);
        PRINT_COUNT(fp, vfadd);
        PRINT_COUNT(fp, vfredusum);
        PRINT_COUNT(fp, vfsub);
        PRINT_COUNT(fp, vfredosum);
        PRINT_COUNT(fp, vfmin);
        PRINT_COUNT(fp, vfredmin);
        PRINT_COUNT(fp, vfmax);
        PRINT_COUNT(fp, vfredmax);
        PRINT_COUNT(fp, vfsgnj);
        PRINT_COUNT(fp, vfsgnjn);
        PRINT_COUNT(fp, vfsgnjx);
        PRINT_COUNT(fp, vwfunary0_dispatch);
        PRINT_COUNT(fp, vmfeq);
        PRINT_COUNT(fp, vmfle);
        PRINT_COUNT(fp, vmflt);
        PRINT_COUNT(fp, vmfne);
        PRINT_COUNT(fp, vfdiv);
        PRINT_COUNT(fp, vfmul);
        PRINT_COUNT(fp, vfmadd);
        PRINT_COUNT(fp, vfnmadd);
        PRINT_COUNT(fp, vfmsub);
        PRINT_COUNT(fp, vfnmsub);
        PRINT_COUNT(fp, vfmacc);
        PRINT_COUNT(fp, vfnmacc);
        PRINT_COUNT(fp, vfmsac);
        PRINT_COUNT(fp, vfnmsac);
        PRINT_COUNT(fp, vfwadd);
        PRINT_COUNT(fp, vfwredusum);
        PRINT_COUNT(fp, vfwsub);
        PRINT_COUNT(fp, vfwredosum);
        PRINT_COUNT(fp, vfwadd_w);
        PRINT_COUNT(fp, vfwsub_w);
        PRINT_COUNT(fp, vfwmul);
        PRINT_COUNT(fp, vfwmacc);
        PRINT_COUNT(fp, vfwnmacc);
        PRINT_COUNT(fp, vfwmsac);
        PRINT_COUNT(fp, vfwnmsac);
        PRINT_COUNT(fp, vfslide1up);
        PRINT_COUNT(fp, vfslide1down);
        PRINT_COUNT(fp, vrfunary0_dispatch);
        PRINT_COUNT(fp, vfmerge);
        PRINT_COUNT(fp, vmfgt);
        PRINT_COUNT(fp, vmfge);
        PRINT_COUNT(fp, vfrdiv);
        PRINT_COUNT(fp, vfrsub);
        PRINT_COUNT(fp, vsetvli);
        PRINT_COUNT(fp, vsetivli);
        PRINT_COUNT(fp, vsetvl);
        PRINT_COUNT(fp, vopivv);
        PRINT_COUNT(fp, vopfvv);
        PRINT_COUNT(fp, vopmvv);
        PRINT_COUNT(fp, vopivi);
        PRINT_COUNT(fp, vopivx);
        PRINT_COUNT(fp, vopfvf);
        PRINT_COUNT(fp, vopmvx);
        PRINT_COUNT(fp, vsetvl_dispatch);   
           
        PRINT_LS_COUNT(fp, vle);     
        PRINT_LS_COUNT(fp, vleff);   
        PRINT_LS_COUNT(fp, vlr);      
        PRINT_LS_COUNT(fp, vlm);     
        PRINT_LS_COUNT(fp, vlxe);    
        PRINT_LS_COUNT(fp, vlse);     
        PRINT_LS_COUNT(fp, vse);     
        PRINT_LS_COUNT(fp, vsr);       
        PRINT_LS_COUNT(fp, vsm);     
        PRINT_LS_COUNT(fp, vsxe);    
        PRINT_LS_COUNT(fp, vsse);      
        PRINT_LS_COUNT(fp, vle_mmu); 
        PRINT_LS_COUNT(fp, vleff_mmu);
        PRINT_LS_COUNT(fp, vlr_mmu); 
        PRINT_LS_COUNT(fp, vlm_mmu); 
        PRINT_LS_COUNT(fp, vlxe_mmu);
        PRINT_LS_COUNT(fp, vlse_mmu);
        PRINT_LS_COUNT(fp, vse_mmu); 
        PRINT_LS_COUNT(fp, vsr_mmu); 
        PRINT_LS_COUNT(fp, vsm_mmu); 
        PRINT_LS_COUNT(fp, vsxe_mmu);
        PRINT_LS_COUNT(fp, vsse_mmu);
    fclose(fp);
    return 0;
}

// COUNTER_FUNCS
    COUNTER_FUNC(vmvxs);
    COUNTER_FUNC(vpopc);
    COUNTER_FUNC(vfirst);
    COUNTER_FUNC(vmvsx);
    COUNTER_FUNC(vzextvf8);
    COUNTER_FUNC(vsextvf8);
    COUNTER_FUNC(vzextvf4);
    COUNTER_FUNC(vsextvf4);
    COUNTER_FUNC(vzextvf2);
    COUNTER_FUNC(vsextvf2);
    COUNTER_FUNC(vbrev_v);
    COUNTER_FUNC(vbrev8_v);
    COUNTER_FUNC(vrev8_v);
    COUNTER_FUNC(vclz_v);
    COUNTER_FUNC(vcpop_v);
    COUNTER_FUNC(vctz_v);
    COUNTER_FUNC(vmsbf);
    COUNTER_FUNC(vmsof);
    COUNTER_FUNC(vmsif);
    COUNTER_FUNC(viota);
    COUNTER_FUNC(vid);
    COUNTER_FUNC(vfmvfs);
    COUNTER_FUNC(vfmvsf);
    COUNTER_FUNC(vfcvt_xufv);
    COUNTER_FUNC(vfcvt_xfv);
    COUNTER_FUNC(vfcvt_fxuv);
    COUNTER_FUNC(vfcvt_fxv);
    COUNTER_FUNC(vfcvt_rtz_xufv);
    COUNTER_FUNC(vfcvt_rtz_xfv);
    COUNTER_FUNC(vfwcvt_xufv);
    COUNTER_FUNC(vfwcvt_xfv);
    COUNTER_FUNC(vfwcvt_fxuv);
    COUNTER_FUNC(vfwcvt_fxv);
    COUNTER_FUNC(vfwcvt_ffv);
    COUNTER_FUNC(vfwcvt_rtz_xufv);
    COUNTER_FUNC(vfwcvt_rtz_xfv);
    COUNTER_FUNC(vfncvt_xufw);
    COUNTER_FUNC(vfncvt_xfw);
    COUNTER_FUNC(vfncvt_fxuw);
    COUNTER_FUNC(vfncvt_fxw);
    COUNTER_FUNC(vfncvt_ffw);
    COUNTER_FUNC(vfncvt_rod_ffw);
    COUNTER_FUNC(vfncvt_rtz_xufw);
    COUNTER_FUNC(vfncvt_rtz_xfw);
    COUNTER_FUNC(vfsqrt_v);
    COUNTER_FUNC(vfrsqrt7_v);
    COUNTER_FUNC(vfrec7_v);
    COUNTER_FUNC(vfclass_v);
    COUNTER_FUNC(vadd);
    COUNTER_FUNC(vsub);
    COUNTER_FUNC(vrsub);
    COUNTER_FUNC(vminu);
    COUNTER_FUNC(vmin);
    COUNTER_FUNC(vmaxu);
    COUNTER_FUNC(vmax);
    COUNTER_FUNC(vand);
    COUNTER_FUNC(vor);
    COUNTER_FUNC(vxor);
    COUNTER_FUNC(vrgather);
    COUNTER_FUNC(vrgatherei16);
    COUNTER_FUNC(vadc);
    COUNTER_FUNC(vmadc);
    COUNTER_FUNC(vsbc);
    COUNTER_FUNC(vmsbc);
    COUNTER_FUNC(vmerge);
    COUNTER_FUNC(vmseq);
    COUNTER_FUNC(vmsne);
    COUNTER_FUNC(vmsltu);
    COUNTER_FUNC(vmslt);
    COUNTER_FUNC(vmsleu);
    COUNTER_FUNC(vmsle);
    COUNTER_FUNC(vmsgtu);
    COUNTER_FUNC(vmsgt);
    COUNTER_FUNC(vsaddu);
    COUNTER_FUNC(vsadd);
    COUNTER_FUNC(vssubu);
    COUNTER_FUNC(vssub);
    COUNTER_FUNC(vsll);
    COUNTER_FUNC(vmvnr);
    COUNTER_FUNC(vsmul);
    COUNTER_FUNC(vsrl);
    COUNTER_FUNC(vsra);
    COUNTER_FUNC(vssra);
    COUNTER_FUNC(vnsrl);
    COUNTER_FUNC(vnsra);
    COUNTER_FUNC(vnclipu);
    COUNTER_FUNC(vnclip);
    COUNTER_FUNC(vssrl);
    COUNTER_FUNC(vwredsumu);
    COUNTER_FUNC(vwredsum);
    COUNTER_FUNC(vdotu);
    COUNTER_FUNC(vdot);
    COUNTER_FUNC(vwsmaccu);
    COUNTER_FUNC(vwsmacc);
    COUNTER_FUNC(vwsmaccsu);
    COUNTER_FUNC(vwsmaccus);
    COUNTER_FUNC(vandn);
    COUNTER_FUNC(vrol);
    COUNTER_FUNC(vror);
    COUNTER_FUNC(vwsll);
    COUNTER_FUNC(vslideup);
    COUNTER_FUNC(vslidedown);
    COUNTER_FUNC(vredsum);
    COUNTER_FUNC(vredand);
    COUNTER_FUNC(vredor);
    COUNTER_FUNC(vredxor);
    COUNTER_FUNC(vredminu);
    COUNTER_FUNC(vredmin);
    COUNTER_FUNC(vredmaxu);
    COUNTER_FUNC(vredmax);
    COUNTER_FUNC(vaaddu);
    COUNTER_FUNC(vaadd);
    COUNTER_FUNC(vasubu);
    COUNTER_FUNC(vasub);
    COUNTER_FUNC(vwxunary0_dispatch);
    COUNTER_FUNC(vmunary0_dispatch);
    COUNTER_FUNC(vcompress);
    COUNTER_FUNC(vmandnot);
    COUNTER_FUNC(vmand);
    COUNTER_FUNC(vmor);
    COUNTER_FUNC(vmxor);
    COUNTER_FUNC(vmornot);
    COUNTER_FUNC(vmnand);
    COUNTER_FUNC(vmnor);
    COUNTER_FUNC(vmxnor);
    COUNTER_FUNC(vdivu);
    COUNTER_FUNC(vdiv);
    COUNTER_FUNC(vremu);
    COUNTER_FUNC(vrem);
    COUNTER_FUNC(vmulhu);
    COUNTER_FUNC(vmul);
    COUNTER_FUNC(vmulhsu);
    COUNTER_FUNC(vmulh);
    COUNTER_FUNC(vmadd);
    COUNTER_FUNC(vnmsub);
    COUNTER_FUNC(vmacc);
    COUNTER_FUNC(vnmsac);
    COUNTER_FUNC(vwaddu);
    COUNTER_FUNC(vwadd);
    COUNTER_FUNC(vwsubu);
    COUNTER_FUNC(vwsub);
    COUNTER_FUNC(vwaddu_w);
    COUNTER_FUNC(vwadd_w);
    COUNTER_FUNC(vwsubu_w);
    COUNTER_FUNC(vwsub_w);
    COUNTER_FUNC(vwmulu);
    COUNTER_FUNC(vwmulsu);
    COUNTER_FUNC(vwmul);
    COUNTER_FUNC(vwmaccu);
    COUNTER_FUNC(vwmacc);
    COUNTER_FUNC(vwmaccus);
    COUNTER_FUNC(vwmaccsu);
    COUNTER_FUNC(vslide1up);
    COUNTER_FUNC(vslide1down);
    COUNTER_FUNC(vrxunary0_dispatch);
    COUNTER_FUNC(vfadd);
    COUNTER_FUNC(vfredusum);
    COUNTER_FUNC(vfsub);
    COUNTER_FUNC(vfredosum);
    COUNTER_FUNC(vfmin);
    COUNTER_FUNC(vfredmin);
    COUNTER_FUNC(vfmax);
    COUNTER_FUNC(vfredmax);
    COUNTER_FUNC(vfsgnj);
    COUNTER_FUNC(vfsgnjn);
    COUNTER_FUNC(vfsgnjx);
    COUNTER_FUNC(vwfunary0_dispatch);
    COUNTER_FUNC(vmfeq);
    COUNTER_FUNC(vmfle);
    COUNTER_FUNC(vmflt);
    COUNTER_FUNC(vmfne);
    COUNTER_FUNC(vfdiv);
    COUNTER_FUNC(vfmul);
    COUNTER_FUNC(vfmadd);
    COUNTER_FUNC(vfnmadd);
    COUNTER_FUNC(vfmsub);
    COUNTER_FUNC(vfnmsub);
    COUNTER_FUNC(vfmacc);
    COUNTER_FUNC(vfnmacc);
    COUNTER_FUNC(vfmsac);
    COUNTER_FUNC(vfnmsac);
    COUNTER_FUNC(vfwadd);
    COUNTER_FUNC(vfwredusum);
    COUNTER_FUNC(vfwsub);
    COUNTER_FUNC(vfwredosum);
    COUNTER_FUNC(vfwadd_w);
    COUNTER_FUNC(vfwsub_w);
    COUNTER_FUNC(vfwmul);
    COUNTER_FUNC(vfwmacc);
    COUNTER_FUNC(vfwnmacc);
    COUNTER_FUNC(vfwmsac);
    COUNTER_FUNC(vfwnmsac);
    COUNTER_FUNC(vfslide1up);
    COUNTER_FUNC(vfslide1down);
    COUNTER_FUNC(vrfunary0_dispatch);
    COUNTER_FUNC(vfmerge);
    COUNTER_FUNC(vmfgt);
    COUNTER_FUNC(vmfge);
    COUNTER_FUNC(vfrdiv);
    COUNTER_FUNC(vfrsub);
    COUNTER_FUNC(vsetvli);
    COUNTER_FUNC(vsetivli);
    COUNTER_FUNC(vsetvl);
    COUNTER_FUNC(vopivv);
    COUNTER_FUNC(vopfvv);
    COUNTER_FUNC(vopmvv);
    COUNTER_FUNC(vopivi);
    COUNTER_FUNC(vopivx);
    COUNTER_FUNC(vopfvf);
    COUNTER_FUNC(vopmvx);
    COUNTER_FUNC(vsetvl_dispatch); 

    COUNTER_LS_FUNC(vle);     
    COUNTER_LS_FUNC(vleff);   
    COUNTER_LS_FUNC(vlr);      
    COUNTER_LS_FUNC(vlm);     
    COUNTER_LS_FUNC(vlxe);    
    COUNTER_LS_FUNC(vlse);     
    COUNTER_LS_FUNC(vse);     
    COUNTER_LS_FUNC(vsr);       
    COUNTER_LS_FUNC(vsm);     
    COUNTER_LS_FUNC(vsxe);    
    COUNTER_LS_FUNC(vsse);      
    COUNTER_LS_FUNC(vle_mmu); 
    COUNTER_LS_FUNC(vleff_mmu)
    COUNTER_LS_FUNC(vlr_mmu); 
    COUNTER_LS_FUNC(vlm_mmu); 
    COUNTER_LS_FUNC(vlxe_mmu);
    COUNTER_LS_FUNC(vlse_mmu);
    COUNTER_LS_FUNC(vse_mmu); 
    COUNTER_LS_FUNC(vsr_mmu); 
    COUNTER_LS_FUNC(vsm_mmu); 
    COUNTER_LS_FUNC(vsxe_mmu);
    COUNTER_LS_FUNC(vsse_mmu);
#endif